name = "fhionnghaile-sqlalchemy-database"
version = "0.0.1"
dependencies = [
]
requires-python = ">= 3.0"
description = "A package for creating a single SQLAlchemy database connection in Flask between modules."

